version: "3.4"

services:
    db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=change-me
            - MYSQL_DATABASE=smandpartners-test

    php:
        build: .
        links:
            - db
        depends_on:
            - db
        volumes:
            - .:/var/www/html
        command: ["bash", "/root/run.sh"]
        environment:
            - DATABASE_HOST=db
            - DATABASE_USER=root
            - DATABASE_PORT=3306
            - DATABASE_PASSWORD=change-me
            - DATABASE_NAME=smandpartners-test

    web:
        image: nginx
        links:
            - db
            - php
        depends_on:
            - db
            - php
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d/
            - .:/var/www/html
        ports:
            - "8080:80"
